/* Generates src/navmask-data.ts from the arena paintings.
 *
 * The collision/terrain mask is baked OFFLINE so every client shares an
 * identical world (runtime image decoding varies subtly across browsers,
 * which would break lockstep determinism).
 *
 * Cell codes: 0 walk · 1 blocked (lava / border rock) · 2 vent
 *             3 sand · 4 shallow water · 5 deep water
 * Grid: 72 x 120 cells over the 9 x 15 world (8 cells per world unit).
 * Run: node scripts/gen-navmask.mjs */
import sharp from 'sharp';
import fs from 'node:fs';

const GW = 72;
const GH = 120;

async function classify(file, kind) {
  const { data, info } = await sharp(file)
    .resize(GW, GH, { fit: 'fill' })
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const cells = new Uint8Array(GW * GH);
  for (let i = 0; i < GW * GH; i++) {
    const r = data[i * 3];
    const g = data[i * 3 + 1];
    const b = data[i * 3 + 2];
    const gx = i % GW;
    const gy = (i / GW) | 0;

    if (kind === 'basalt') {
      // Bright orange lava.
      const lava = r > 150 && r > g * 1.45 && b < 90;
      // Sulfur vents: acid yellow-green.
      const vent = g > 130 && g > r * 1.1 && b < 90;
      // Rocky border wall: keep a thin inset all around.
      const border = gx < 3 || gx >= GW - 3 || gy < 2 || gy >= GH - 2;
      cells[i] = border ? 1 : lava ? 1 : vent ? 2 : 0;
    } else {
      const border = gx < 2 || gx >= GW - 2 || gy < 2 || gy >= GH - 2;
      // Water: blue dominant over red.
      const water = b > 95 && b > r * 1.25 && g > 60;
      const deep = water && b > 120 && r < 60;
      // Wet sand ring: warm tan.
      const sand = !water && r > 120 && r > b * 1.5 && g > 90 && g < r * 0.95;
      cells[i] = border ? 0 : deep ? 5 : water ? 4 : sand ? 3 : 0;
    }
  }

  // Cleanup: majority filter to remove speckle.
  const out = new Uint8Array(cells);
  for (let y = 1; y < GH - 1; y++) {
    for (let x = 1; x < GW - 1; x++) {
      const i = y * GW + x;
      const counts = new Map();
      for (let dy = -1; dy <= 1; dy++) {
        for (let dx = -1; dx <= 1; dx++) {
          const v = cells[(y + dy) * GW + (x + dx)];
          counts.set(v, (counts.get(v) ?? 0) + 1);
        }
      }
      let best = cells[i];
      let bestN = 0;
      for (const [v, n] of counts) {
        if (n > bestN) {
          bestN = n;
          best = v;
        }
      }
      out[i] = best;
    }
  }
  return out;
}

function ascii(cells) {
  const chars = ['.', '#', 'V', 's', 'w', 'D'];
  let s = '';
  for (let y = 0; y < GH; y += 2) {
    for (let x = 0; x < GW; x += 1) s += chars[cells[y * GW + x]];
    s += '\n';
  }
  return s;
}

const basalt = await classify('art-src/arena1.png', 'basalt');
const oasis = await classify('art-src/arena2.png', 'oasis');

console.log('=== BASALT ===');
console.log(ascii(basalt));
console.log('=== OASIS ===');
console.log(ascii(oasis));

const enc = (cells) => Buffer.from(cells).toString('base64');

fs.writeFileSync(
  'src/navmask-data.ts',
  `/* AUTO-GENERATED by scripts/gen-navmask.mjs — do not edit by hand.
 * Terrain masks sampled from the arena paintings (72x120 cells over the
 * 9x15 world). Codes: 0 walk, 1 blocked, 2 vent, 3 sand, 4 shallow, 5 deep. */
export const NAV_GW = ${GW};
export const NAV_GH = ${GH};
export const BASALT_MASK_B64 = '${enc(basalt)}';
export const OASIS_MASK_B64 = '${enc(oasis)}';
`,
);
console.log('wrote src/navmask-data.ts');
